--
-- PostgreSQL database dump
--

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-03-21 16:34:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16526)
-- Name: caracteristica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caracteristica (
    id bigint NOT NULL,
    nombre character varying(255),
    padre_id bigint
);


ALTER TABLE public.caracteristica OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16525)
-- Name: caracteristica_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caracteristica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caracteristica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16533)
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresa (
    id bigint NOT NULL,
    aprobado boolean NOT NULL,
    correo character varying(255),
    descripcion character varying(255),
    localizacion character varying(255),
    nombre character varying(255),
    password character varying(255),
    telefono character varying(255)
);


ALTER TABLE public.empresa OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16532)
-- Name: empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16543)
-- Name: habilidad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.habilidad (
    id bigint NOT NULL,
    nivel integer NOT NULL,
    caracteristica_id bigint,
    oferente_id bigint
);


ALTER TABLE public.habilidad OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16542)
-- Name: habilidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.habilidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habilidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16551)
-- Name: oferente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oferente (
    id bigint NOT NULL,
    aprobado boolean NOT NULL,
    correo character varying(255),
    cv_path character varying(255),
    identificacion character varying(255),
    nacionalidad character varying(255),
    nombre character varying(255),
    password character varying(255),
    primer_apellido character varying(255),
    residencia character varying(255),
    telefono character varying(255)
);


ALTER TABLE public.oferente OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16550)
-- Name: oferente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oferente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oferente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16561)
-- Name: puesto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.puesto (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    descripcion character varying(255),
    publico boolean NOT NULL,
    salario double precision,
    empresa_id bigint,
    fecha_creacion date
);


ALTER TABLE public.puesto OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16560)
-- Name: puesto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.puesto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.puesto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16570)
-- Name: requisito_puesto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requisito_puesto (
    id bigint NOT NULL,
    nivel_requerido integer NOT NULL,
    caracteristica_id bigint,
    puesto_id bigint
);


ALTER TABLE public.requisito_puesto OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16569)
-- Name: requisito_puesto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.requisito_puesto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requisito_puesto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5047 (class 0 OID 16526)
-- Dependencies: 220
-- Data for Name: caracteristica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caracteristica (id, nombre, padre_id) FROM stdin;
1	Java	\N
2	Lenguajes de Programacion	\N
3	Python	2
\.


--
-- TOC entry 5049 (class 0 OID 16533)
-- Dependencies: 222
-- Data for Name: empresa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empresa (id, aprobado, correo, descripcion, localizacion, nombre, password, telefono) FROM stdin;
1	t	jsv_inc@gmail.com	JSV Inc.	Desamparados	JSV Inc.	jsv_inc@gmail.com	0000-0000
\.


--
-- TOC entry 5051 (class 0 OID 16543)
-- Dependencies: 224
-- Data for Name: habilidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.habilidad (id, nivel, caracteristica_id, oferente_id) FROM stdin;
1	1	3	1
2	5	1	1
\.


--
-- TOC entry 5053 (class 0 OID 16551)
-- Dependencies: 226
-- Data for Name: oferente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.oferente (id, aprobado, correo, cv_path, identificacion, nacionalidad, nombre, password, primer_apellido, residencia, telefono) FROM stdin;
1	t	isaac.naranjo@gmail.com	cvs/1_cv.pdf	1111	Costarricense	Isaac	1111	Naranjo	Costa Ricca	1111-1111
\.


--
-- TOC entry 5055 (class 0 OID 16561)
-- Dependencies: 228
-- Data for Name: puesto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.puesto (id, activo, descripcion, publico, salario, empresa_id, fecha_creacion) FROM stdin;
1	f	Full Stack Developer	t	100000	1	2026-03-21
2	t	Full Stack Developer	t	100000	1	2026-03-21
\.


--
-- TOC entry 5057 (class 0 OID 16570)
-- Dependencies: 230
-- Data for Name: requisito_puesto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.requisito_puesto (id, nivel_requerido, caracteristica_id, puesto_id) FROM stdin;
4	3	1	7
5	3	1	8
\.


--
-- TOC entry 5063 (class 0 OID 0)
-- Dependencies: 219
-- Name: caracteristica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caracteristica_id_seq', 3, true);


--
-- TOC entry 5064 (class 0 OID 0)
-- Dependencies: 221
-- Name: empresa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empresa_id_seq', 1, true);


--
-- TOC entry 5065 (class 0 OID 0)
-- Dependencies: 223
-- Name: habilidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.habilidad_id_seq', 2, true);


--
-- TOC entry 5066 (class 0 OID 0)
-- Dependencies: 225
-- Name: oferente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oferente_id_seq', 1, true);


--
-- TOC entry 5067 (class 0 OID 0)
-- Dependencies: 227
-- Name: puesto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.puesto_id_seq', 8, true);


--
-- TOC entry 5068 (class 0 OID 0)
-- Dependencies: 229
-- Name: requisito_puesto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.requisito_puesto_id_seq', 5, true);


--
-- TOC entry 4882 (class 2606 OID 16531)
-- Name: caracteristica caracteristica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caracteristica
    ADD CONSTRAINT caracteristica_pkey PRIMARY KEY (id);


--
-- TOC entry 4884 (class 2606 OID 16541)
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);


--
-- TOC entry 4886 (class 2606 OID 16549)
-- Name: habilidad habilidad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habilidad
    ADD CONSTRAINT habilidad_pkey PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 16559)
-- Name: oferente oferente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferente
    ADD CONSTRAINT oferente_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 16568)
-- Name: puesto puesto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto
    ADD CONSTRAINT puesto_pkey PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 16576)
-- Name: requisito_puesto requisito_puesto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requisito_puesto
    ADD CONSTRAINT requisito_puesto_pkey PRIMARY KEY (id);


--
-- TOC entry 4894 (class 2606 OID 16587)
-- Name: habilidad fkd3bbai6dafd1sroiegdscfob3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habilidad
    ADD CONSTRAINT fkd3bbai6dafd1sroiegdscfob3 FOREIGN KEY (oferente_id) REFERENCES public.oferente(id);


--
-- TOC entry 4893 (class 2606 OID 16577)
-- Name: caracteristica fkh4vgjxhaq6fwbvrs3hxoeuus7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caracteristica
    ADD CONSTRAINT fkh4vgjxhaq6fwbvrs3hxoeuus7 FOREIGN KEY (padre_id) REFERENCES public.caracteristica(id);


--
-- TOC entry 4896 (class 2606 OID 16592)
-- Name: puesto fkn5jgwg4anw6yj1lrv2ii7es0a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto
    ADD CONSTRAINT fkn5jgwg4anw6yj1lrv2ii7es0a FOREIGN KEY (empresa_id) REFERENCES public.empresa(id);


--
-- TOC entry 4897 (class 2606 OID 16597)
-- Name: requisito_puesto fkoa4srpjhdxb4wdrogcmsfht1l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requisito_puesto
    ADD CONSTRAINT fkoa4srpjhdxb4wdrogcmsfht1l FOREIGN KEY (caracteristica_id) REFERENCES public.caracteristica(id);


--
-- TOC entry 4898 (class 2606 OID 16602)
-- Name: requisito_puesto fkpdsnrbliwmo86yvpnwp6nl2tn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requisito_puesto
    ADD CONSTRAINT fkpdsnrbliwmo86yvpnwp6nl2tn FOREIGN KEY (puesto_id) REFERENCES public.puesto(id);


--
-- TOC entry 4895 (class 2606 OID 16582)
-- Name: habilidad fkqkpek3nvjib2tm36bv193c53k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habilidad
    ADD CONSTRAINT fkqkpek3nvjib2tm36bv193c53k FOREIGN KEY (caracteristica_id) REFERENCES public.caracteristica(id);


-- Completed on 2026-03-21 16:34:45

--
-- PostgreSQL database dump complete
--

