spring.application.name=Proyecto_Programacion_IV_Bolsa_Empleo

spring.datasource.url=jdbc:postgresql://localhost:5433/bolsa_empleo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false